service:
  url:
    movieNameService: ${movieNameServiceUrl:http://localhost:8082/movies/}
server:
  port: ${PORT:8080}
spring:
  application:
    name: FindMovies_FrontEnd
  web:
    resources:
      static-locations: classpath:/static/
