eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://admin:password@localhost:8761/eureka
MovieNameService:
  url: http://MovieNameService/movies/
server:
  port: ${PORT:8081}
spring:
  application:
    name: FindMovies_FrontEnd
  mvc:
    view:
      prefix: /webapp/views/
      suffix: .html
